getmakerecipe config to CSV; added simple test

diff --git a/.local/bin/getmakerecipe b/.local/bin/getmakerecipe
--- a/.local/bin/getmakerecipe
+++ b/.local/bin/getmakerecipe
@@ -1,7 +1,29 @@
 #!/bin/sh
 
 # Author: Matthew Ellis
+# Description: Build a make recipe from a source file
 
+# exit immediately if a pipeline, a list, or a compound command returns
+# non-zero status
+set -e
+
+#### Variables
+
+# Defaults
+DEFAULT_CSL="journal-of-process-control.csl"
+DEFAULT_FROM="markdown+latex_macros+link_attributes"
+DEFAULT_PDF_ENGINE="latexmk"
+DEFAULT_HIGHLIGHT="tango"
+DEFAULT_TEMPLATE="default.latex"
+CONFIG="${HOME}/.local/bin/default_config.csv"
+BLDDIR=.make
+DISTDIR=dist
+DIST_TEX_SUPPORT='(eps|png|jpg|jpeg|pdf|bib)'
+MAX_DEPTH=5
+
+#### Functions
+
+## Utility functions
 usage() {
 	# Print usage
 	echo "Automatically generate a make recipe from a source file"
@@ -15,29 +37,6 @@ usage() {
 	echo "h		Print this help"
 }
 
-# Defaults
-DEFAULT_CSL="journal-of-process-control.csl"
-DEFAULT_FROM="markdown+latex_macros+link_attributes"
-DEFAULT_PDF_ENGINE="latexmk"
-DEFAULT_HIGHLIGHT="tango"
-DEFAULT_TEMPLATE="default.latex"
-BLDDIR=.make
-DISTDIR=dist
-DIST_TEX_SUPPORT='(eps|png|jpg|jpeg|pdf|bib)'
-# ext, default output, default recipe, start comment, end comment,
-# !end-build before or after comment mark
-BUILD='.md,pdf,pandoc_pdf,<!--,-->,false
-.py,eps,python,#,#,true
-.ipynb,eps,jupyter_notebooks,<!--,-->,false
-.m,eps,matlab,%,%,true
-.tex,pdf,latex_pdf,%,%,true'
-
-# Parse inputs
-[[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]] && usage && exit
-SRC="$1"
-
-
-## Utility functions
 get_instruction () {
 	# Get the instruction from the instruction list
 	local result=`echo "${INSTRUCTIONS}" | sed -n "${PREFIX}${1}:${SUFFIX}" | tr '\n' ' '`
@@ -59,8 +58,6 @@ contains () {
 	}
 	echo false
 }
-
-MAX_DEPTH=5
 
 get_dependencies ()
 {
@@ -353,16 +350,23 @@ octave () {
 
 #TODO: automatic builds of virtualenvs
 
+#### Parse inputs
+
+# Parse inputs
+[[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]] && usage && exit
+SRC="$1"
+
+#### Main
+
 # Base and extension
 BASE=${SRC%.*}
 EXT=.${SRC##*.}
-SRC_BUILD=`echo "$BUILD" | grep -E $EXT,`
 SRCDIR=$(dirname "${SRC}")
 MAKEH=${BLDDIR}/${SRC}.make
 
 # Get all properties
 read DEFAULT_EXT DEFAULT_RECIPE COMMENT_START COMMENT_END AFTER_MARK \
-	<<< $(echo "${SRC_BUILD}" | awk -F ',' '{print $2" "$3" "$4" "$5" "$6}')
+	<<< $(grep "$EXT," "$CONFIG" | awk -F ',' '{print $2" "$3" "$4" "$5" "$6}')
 
 if [ "${AFTER_MARK}" == "true" ]
 then
