Update to Pydev

diff --git a/.local/bin/pydev b/.local/bin/pydev
--- a/.local/bin/pydev
+++ b/.local/bin/pydev
@@ -2,14 +2,43 @@
 #
 # In TMUX, will  create three splits: one for editing code, one for IPython, and other for git
 
-# TODO: check if tmux is open
-# TODO: Modify percentage based on size of the window
-VENV=`find . -wholename '*venv*/*/activate'`
-ACTIVE_PANE=`tmux display-message -p "#{pane_id}"`
+# Check if tmux is open
+if [ -z "$TMUX" ]; then
+  echo "Error: tmux is not running. Please start tmux and run the script inside a tmux session."
+  exit 1
+fi
+
+# Get the window ID of the terminal
+WINDOW_ID=$(xdotool getactivewindow)
+
+# Get the size of the terminal window in pixels
+WINDOW_GEOMETRY=$(xdotool getwindowgeometry $WINDOW_ID | grep -oP '\d+x\d+')
+WINDOW_WIDTH=$(echo $WINDOW_GEOMETRY | cut -d 'x' -f 1)
+WINDOW_HEIGHT=$(echo $WINDOW_GEOMETRY | cut -d 'x' -f 2)
+
+# Approximate cell size (can vary based on terminal and font)
+CELL_WIDTH=8
+CELL_HEIGHT=16
+
+# Calculate the number of cells in the terminal
+CELL_COLUMNS=$(($WINDOW_WIDTH / $CELL_WIDTH))
+CELL_ROWS=$(($WINDOW_HEIGHT / $CELL_HEIGHT))
+
+# Determine the sizes of the panes based on pixel values
+# For example, setting one pane to 30% of the width in pixels
+H_SPLIT_COLUMNS=$(($CELL_COLUMNS * 30 / 100))
+V_SPLIT_ROWS=$(($CELL_ROWS * 50 / 100))
+
+VENV=$(find . -wholename '*venv*/*/activate')
+ACTIVE_PANE=$(tmux display-message -p "#{pane_id}")
+
 tmux send-keys "source ${VENV}" C-m "vim" C-m
 tmux split-window -h
-tmux send-keys "source ${VENV}" C-m "ipython" C-m
+tmux resize-pane -x $H_SPLIT_COLUMNS
+
+tmux send-keys "source ${VENV}" C-m "ipython" C-m "clear" C-m
 tmux split-window -v
-tmux send-keys "source ${VENV}" C-m
-tmux resize-pane -x 30%
+tmux resize-pane -y $V_SPLIT_ROWS
+
+tmux send-keys "source ${VENV}" C-m "clear" C-m
 tmux select-pane -t "${ACTIVE_PANE}"
